name: AzureCLISample

on:
  push:
    branches:
      - 'main'
      - 'dev'

# env:
#   TF_DIR: '/tf_azure'
#   AZURE_FUNCTIONAPP_NAME: tfewc-function
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: EvilWeatherControlApp\published
#   CONFIGURATION: Release
#   DOTNET_VERSION: 6.0.x
#   WORKING_DIRECTORY: EvilWeatherControlApp
#   TESTING_DIRECTORY: EvilWeatherControlApp.Tests

jobs:
  terraform:
    name: "Terraform"
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
 
      - name: 'Setup Terraform'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}         
 
      # - name: 'Terraform Init'
      #   working-directory: ${{ env.TF_DIR }}
      #   id: init
      #   run: terraform init
       
      # - name: 'Terraform Validate'
      #   working-directory: ${{ env.TF_DIR }}
      #   id: validate
      #   run: terraform validate -no-color

      # - name: 'Terraform Plan'
      #   working-directory: ${{ env.TF_DIR }}
      #   id: plan
      #   run: terraform plan -no-color
      #   continue-on-error: true
 
      # - name: 'Terraform Apply'
      #   working-directory: ${{ env.TF_DIR }}
      #   run: terraform apply -auto-approve -input=false

  # build-and-deploy:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Log in with Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az account show
            az storage -h