name: TF_Azure_Functions

on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  TF_DIR: 'tf_azure'
#   AZURE_FUNCTIONAPP_NAME: tfewc-function
#   AZURE_FUNCTIONAPP_PACKAGE_PATH: EvilWeatherControlApp\published
#   CONFIGURATION: Release
#   DOTNET_VERSION: 6.0.x
#   WORKING_DIRECTORY: EvilWeatherControlApp
#   TESTING_DIRECTORY: EvilWeatherControlApp.Tests

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4
 
      - name: 'Terraform Cloud access'
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: 'Enable Terraform debug'
        run: 'export TF_LOG=debug'     
 
      - name: 'Terraform Init'
        working-directory: ${{ env.TF_DIR }}
        id: init
        run: terraform init
       
      - name: 'Terraform Validate'
        working-directory: ${{ env.TF_DIR }}
        id: validate
        run: terraform validate -no-color

      - name: 'Terraform Plan'
        working-directory: ${{ env.TF_DIR }}
        id: plan
        run: terraform plan -no-color
        continue-on-error: true
 
      - name: 'Terraform Apply'
        working-directory: ${{ env.TF_DIR }}
        run: terraform apply -auto-approve -input=false

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Azure Cloud access'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az account show
            az storage -h

# TODO:
# - Compare CORP TF files with this repo
# - SELF-HOSTED RUNNER:
#   - CLI or pre-defined workflows (check action github marketplace)
#     - deploy on-prem Function?

# A common pattern is to have one workflow with separate jobs to build/test, and then deploy. You can put a condition on the deploy job (e.g. "run only on tags").

# If build is ok, move to test, if test is ok, move to deploy: Azure/GCP