name: AzureCLISample

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout'
      uses: actions/checkout@v4

    - name: 'Log in with Azure'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        azcliversion: 2.30.0
        inlineScript: |
            az account show
            az storage -h