name: GCPCLISample

on:
  push:
    branches:
      - 'main'
      - 'dev'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: 'Checkout'
      uses: 'actions/checkout@v4'

    - name: 'Log in with GCP'
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v2'
      with:
        # version: '>= 459.0.0'
        version: 'latest'

    - name: 'Use gcloud CLI'
      run: 'gcloud info'

# IMPLEMENT SELF-HOSTED RUNNER!

# A common pattern is to have one workflow with separate jobs to build/test, and then deploy. You can put a condition on the deploy job (e.g. "run only on tags").

# If build is ok, move to test, if test is ok, move to deploy: Azure/GCP