name: TF_OnPrem

on:
  push:
    branches:
      - 'main'
      - 'dev'

env:
  PYTHON_VERSION: '3.9' 

jobs:
  build:
    runs-on: self-hosted
    steps:

    - name: 'Checkout'
      uses: 'actions/checkout@v4'

    - name: 'Run bash echo command'
      run: echo 'Hello, world!'

    - name: Setup Python ${{ env.PYTHON_VERSION }} Environment
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt